2024-11-23 20:34:00,936 - app - ERROR - Traceback (most recent call last):
  File "/Users/patiforost/CascadeProjects/football-finder/backend/venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/patiforost/CascadeProjects/football-finder/backend/venv/lib/python3.13/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.DependentObjectsStillExist: cannot drop table "user" because other objects depend on it
DETAIL:  constraint game_creator_id_fkey on table game depends on table "user"
HINT:  Use DROP ... CASCADE to drop the dependent objects too.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/patiforost/CascadeProjects/football-finder/backend/app.py", line 194, in <module>
    db.drop_all()
    ~~~~~~~~~~~^^
  File "/Users/patiforost/CascadeProjects/football-finder/backend/venv/lib/python3.13/site-packages/flask_sqlalchemy/extension.py", line 917, in drop_all
    self._call_for_binds(bind_key, "drop_all")
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/patiforost/CascadeProjects/football-finder/backend/venv/lib/python3.13/site-packages/flask_sqlalchemy/extension.py", line 881, in _call_for_binds
    getattr(metadata, op_name)(bind=engine)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/patiforost/CascadeProjects/football-finder/backend/venv/lib/python3.13/site-packages/sqlalchemy/sql/schema.py", line 5896, in drop_all
    bind._run_ddl_visitor(
    ~~~~~~~~~~~~~~~~~~~~~^
        ddl.SchemaDropper, self, checkfirst=checkfirst, tables=tables
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/patiforost/CascadeProjects/football-finder/backend/venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 3253, in _run_ddl_visitor
    conn._run_ddl_visitor(visitorcallable, element, **kwargs)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/patiforost/CascadeProjects/football-finder/backend/venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 2459, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/patiforost/CascadeProjects/football-finder/backend/venv/lib/python3.13/site-packages/sqlalchemy/sql/visitors.py", line 664, in traverse_single
    return meth(obj, **kw)
  File "/Users/patiforost/CascadeProjects/football-finder/backend/venv/lib/python3.13/site-packages/sqlalchemy/sql/ddl.py", line 1076, in visit_metadata
    self.traverse_single(
    ~~~~~~~~~~~~~~~~~~~~^
        table,
        ^^^^^^
    ...<2 lines>...
        _ignore_sequences=seq_coll,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/patiforost/CascadeProjects/football-finder/backend/venv/lib/python3.13/site-packages/sqlalchemy/sql/visitors.py", line 664, in traverse_single
    return meth(obj, **kw)
  File "/Users/patiforost/CascadeProjects/football-finder/backend/venv/lib/python3.13/site-packages/sqlalchemy/sql/ddl.py", line 1143, in visit_table
    DropTable(table)._invoke_with(self.connection)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/patiforost/CascadeProjects/football-finder/backend/venv/lib/python3.13/site-packages/sqlalchemy/sql/ddl.py", line 314, in _invoke_with
    return bind.execute(self)
           ~~~~~~~~~~~~^^^^^^
  File "/Users/patiforost/CascadeProjects/football-finder/backend/venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
        self,
        distilled_parameters,
        execution_options or NO_OPTIONS,
    )
  File "/Users/patiforost/CascadeProjects/football-finder/backend/venv/lib/python3.13/site-packages/sqlalchemy/sql/ddl.py", line 180, in _execute_on_connection
    return connection._execute_ddl(
           ~~~~~~~~~~~~~~~~~~~~~~~^
        self, distilled_params, execution_options
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/patiforost/CascadeProjects/football-finder/backend/venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 1529, in _execute_ddl
    ret = self._execute_context(
        dialect,
    ...<4 lines>...
        compiled,
    )
  File "/Users/patiforost/CascadeProjects/football-finder/backend/venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ~~~~~~~~~~~~~~~~~~~~~~~~~^
        dialect, context, statement, parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/patiforost/CascadeProjects/football-finder/backend/venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        e, str_statement, effective_parameters, cursor, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/patiforost/CascadeProjects/football-finder/backend/venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/Users/patiforost/CascadeProjects/football-finder/backend/venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/patiforost/CascadeProjects/football-finder/backend/venv/lib/python3.13/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.InternalError: (psycopg2.errors.DependentObjectsStillExist) cannot drop table "user" because other objects depend on it
DETAIL:  constraint game_creator_id_fkey on table game depends on table "user"
HINT:  Use DROP ... CASCADE to drop the dependent objects too.

[SQL: 
DROP TABLE "user"]
(Background on this error at: https://sqlalche.me/e/20/2j85)

2024-11-23 20:34:01,235 - app - INFO - Dropping all tables...
2024-11-23 20:34:01,255 - app - ERROR - Error setting up database: (psycopg2.errors.DependentObjectsStillExist) cannot drop table "user" because other objects depend on it
DETAIL:  constraint game_creator_id_fkey on table game depends on table "user"
HINT:  Use DROP ... CASCADE to drop the dependent objects too.

[SQL: 
DROP TABLE "user"]
(Background on this error at: https://sqlalche.me/e/20/2j85)
